### ISSUE TITLE
Fix player spinning during cutscenes

### ISSUE THREAD

**Issue by TWITCHGAMER34** [TWITCHGAMER34/SO4-ARBETSLAG-1#2]
Currently, when starting a cutscene, the player’s ship will keep its angular momentum and spin. It’s not really a bug, but the spinning looks pretty silly and breaks immersion during cutscenes. Make it so that the player’s ship doesn’t spin out of control during cutscenes, for example by cutting angular speed to 0.

**Comment by 69funnny** [comment]
This was fixed in commit e4c0903.

**Comment by 69funnny** [comment]
commit message: 3996f174e5acc78e833d4f0c831545c9a21f1afa

**Comment by 69funnny** [comment]
klart
