### ISSUE TITLE
Make player health persistent, add repair function

### ISSUE THREAD

**Issue by TWITCHGAMER34** [TWITCHGAMER34/SO4-ARBETSLAG-1#4]
Currently, player health and shield values don’t persist across jumps, or after docking and undocking from a station. Player health should persist, and a repair function added to stations, so that the player can repair their ship after combat.

**Comment by Sampis** [comment]
Added a health variable to the character entity that the player ship can get when it's being created. 
For the repair panel I used JunkTraderPanel as a reference and created the ShipRepairPanel, then I added the ShipRepairPanel to the BaseHusPanel. 
I also added the command _takeDamage_ to DebugCommands to make it easier to test the repair function
4852d59ec20e455a274b7d115f25fbbd8c1add66
